swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
paths:
  /user/transactions:
    get:
      security:
          - Bearer: []
      tags: 
        - Transaction module
      summary: Retrieve all transactions from specified account
      responses:
        '200':
          description: A list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      security:
          - Bearer: []
      tags: 
          - Transaction module
      summary: Retrieve specified transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: Transaction Id
      responses:
        '200':
          description: Informations of the specified transaction
          schema:
            $ref: '#/definitions/transactionInformations'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put: 
      security:
        - Bearer: []
      tags: 
        - Transaction module
      summary: Update transaction information
      parameters: 
        - name: transactionId
          in: path
          required: true
          type: string
          description: Transaction Id
        - name: body
          in: body
          description: Update payload
          required: true
          schema:
            $ref: '#/definitions/informationToChange'
      responses: 
        '200':
          description: Information successfully updated
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post: 
      security:
        - Bearer: []
      tags: 
        - Transaction module
      summary: Add transactions information
      parameters: 
        - name: transactionId
          in: path
          required: true
          type: string
          description: Transaction Id
        - name: body
          in: body
          description: Update payload
          required: true
          schema:
            $ref: '#/definitions/informationToAdd'
      responses:
        '200':
          description: Information successfully added
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
          - Bearer: []
      tags: 
        - Transaction module
      summary: Remove a specific information from a transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: The ID of the transaction to update
        - name: information
          in: query
          required: true
          type: string
          enum:
            - name
            - category
            - date
            - note
            - information
          description: The information to remove from the transaction
      responses:
        '200':
          description: Successful removal of the information
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      name: 
        type: string
        description: Nom de la transaction
      note:
        type: string
        description: Description de la transaction
      amount:
        type: number
        format: float
        description: Montant de la transaction
  transactionInformations:
    type: object
    properties: 
      id:
        type: string
        description: Identifiant unique de la transaction
      name: 
        type: string
        description: Nom de la transaction
      category: 
        type: string
        description: Catégorie de la transaction
      date: 
        type: string
        format: date
        description: Date de la transaction
      note:
        type: string
        description: Description de la transaction
      amount:
        type: number
        format: float
        description: Montant de la transaction
  informationToChange:
    type: object
    properties: 
      name: 
        type: string
        description: Nom de la transaction
      category: 
        type: string
        description: Catégorie de la transaction
      note:
        type: string
        description: Description de la transaction
  informationToAdd:
    type: object
    properties: 
      information: 
        type: string
        description: Nouvelle information
