swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Retrieve all transactions from specified account
      description: View all transactions for the current month, grouped by account
      responses:
        '200':
          description: A list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/transaction'
        '401':
          description: Invalid Token
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Retrieve specified transaction
      description: View the details of a transaction in another view
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: Transaction Id
      responses:
        '200':
          description: Informations of the specified transaction
          schema:
            $ref: '#/definitions/transactionInformations'
        '401':
          description: Invalid Token
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Update transaction information
      description: Add, modify or delete information about a transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: Transaction Id
        - name: body
          in: body
          description: Update payload
          required: true
          schema:
            $ref: '#/definitions/informationToChange'
      responses:
        '200':
          description: Information successfully updated
        '400':
          description: Invalid field
        '401':
          description: Invalid Token
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      name:
        type: string
        description: Nom de la transaction
      note:
        type: string
        description: Description de la transaction
      amount:
        type: number
        format: float
        description: Montant de la transaction
  transactionInformations:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      name:
        type: string
        description: Nom de la transaction
      category:
        type: string
        description: Catégorie de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      note:
        type: string
        description: Description de la transaction
      amount:
        type: number
        format: float
        description: Montant de la transaction
  informationToChange:
    type: object
    properties:
      category:
        type: string
        description: Catégorie de la transaction
      note:
        type: string
        description: Description de la transaction
